### ISSUE TITLE
Research build system and code generation

### ISSUE THREAD

**Issue by jmealo** [jmealo/random-ua.js#5]
Perhaps random-ua should be built using grunt. Instead of hard coded values, the bulk of the code could be auto-generated using a set of files describing how to build the various user agent and operating system strings. Then one could build random-ua with or without mobile support.

**Comment by masterT** [comment]
Why know it use a prebuilt data file, something like https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json ?
